### ISSUE TITLE
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The value provided is neither an array, nor does it have indexed properties.

### ISSUE THREAD

**Issue by hashworks** [STRML/Imgur-to-Gfycat#21]
This console error happens on every website I visit.
imgur-to-gfycat.js:41

**Comment by STRML** [comment]
Thanks. Will look into it.

**Comment by STRML** [comment]
Interesting. `attributeFilter` is now required to be an array in the final spec.

**Comment by STRML** [comment]
Published as `1.4.7`.
